title = "SABER Configurations"

[dataset]
# root = "/media/vigi99/ssd_1tb/AudioData/cv-corpus-6.1-2020-12-11/en"
root = "/dev/shm/cv-corpus-6.1-2020-12-11/en"
train = "validated.tsv"
test = "test.tsv"
unsupervised_train = "unsupervised_train.tsv"
supervised_train = "supervised_train.tsv"
percent_split = 9
sample_rate = 48000
max_audio_in_s = 13.0
min_audio_in_s = 2.0

[trainer]
# default_root_dir = "/media/vigi99/ssd_1tb/AudioWorkdir/SABERv2/training_artifacts"
default_root_dir = "/tts_data/SABERV2/training_artifacts"
tensorboard_logdir = "tb_logs"
savewieghts_dir = "weights"
max_epochs = 150
num_gpus = 3
num_nodes = 1
precision = 32
log_every_n_steps = 50
gradient_clip_val = 0.5
fast_dev_run = false
start_lr = 5e-4
final_lr = 1e-4
learning_rate = 1e-3
warmup_epochs = 3.0
weight_decay = 1e-6

[dataloader]
batch_size = 48
num_workers = 32

[audio]
n_mels = 80
window_size_in_ms = 25
stride_in_ms = 10
model_sample_rate = 8000

[augmentations]
vol_range_in_db = [-25, 10]
pitch_range_in_cents = [-400, 400]
lowpass_cutoff = [1500, 4000]
tempo_range = [0.8, 1.3]
apply_prob = 0.5

[spec_aug]
freq_len = 27
time_len = 100
freq_n = 1
time_n = 1

[noises]
# noises_root = "/media/vigi99/ssd_1tb/AudioData/noises"
noises_root = "/dev/shm/noises"
noisefilelist = "noiselist.txt"
snr_range = [3, 20]

[simclr]
projection_head_dim = 1024
final_embedding_dim = 128
temperature = 0.1
margin = 0.35